version: "3.8"

services:
    frontend:
        build: 
            context: ./frontend
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - MONGO_URI=mongodb://mongodb:27017/ride-hailing
        env_file:
            - ./frontend/.env
        depends_on:
            - backend

    backend:
        build: 
            context: ./backend
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/app
        env_file:
            - ./backend/.env
        depends_on:
            - mongodb

    mongodb:
        image: mongo:8
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
